### ISSUE TITLE
Add the ability to add multiple sliders

### ISSUE THREAD

**Issue by chrisnharvey** [mamarmite/PyroCMS-Slider-Module#1]
It would be great if we could have multiple sliders and not just one. Would also be pretty cool if we could restrict clients from adding and deleting sliders using permissions.

**Comment by mamarmite** [comment]
I made a branch with that functionality.
https://github.com/mamarmite/PyroCMS-Slider-Module/tree/Multi-Sliders

I'm open to all point of view for the better implementation.

**Comment by mamarmite** [comment]
I made multiple changes to the module. I add the user's permissions to the multiples sliders parts.
https://github.com/mamarmite/PyroCMS-Slider-Module/tree/Multi-Sliders

Would you like a pull request? It may have a lot of merge conflitcs.

**Comment by chrisnharvey** [comment]
Hey,

Many thanks for your message.

Looks like you've done a pretty good job of extending this module.

I am no longer developing this module. So I'm happy to transfer this repository to you if you would like to maintain it?

**Comment by mamarmite** [comment]
Hi, Chris, I will be please to maintain it. 
What are the steps to do that though?

**Comment by chrisnharvey** [comment]
Hi @mamarmite,

I'll transfer this repository to you now. The only think I ask is that you mention that I was the original author in the license file and it has the MIT license.

Cheers,

Chris

**Comment by chrisnharvey** [comment]
I'll add the license file now.

I tried transferring this repository to you, but it failed because you already have a repository named "PyroCMS-Slider-Module". If you could rename or delete this repository and let me know, then I'll transfer this one to you.

**Comment by mamarmite** [comment]
Ok, I deleted my fork of the project.
Thanks!

**Comment by chrisnharvey** [comment]
Brilliant! I have started the transfer process.

**Comment by chrisnharvey** [comment]
All done! Looking forward to see what you do with this plugin.

I'm really glad you're able to maintain it.
